=== MarkJov/ist2021/XML/proizvodi.dtd
<!ELEMENT Proizvodi (Proizvod)*>
<!ELEMENT Proizvod (Kategorija,Cena,TekstOglasa,Oznake,Akcije)>
<!ELEMENT Kategorija (#PCDATA)>
<!ELEMENT Cena (#PCDATA)>
<!ELEMENT TekstOglasa (#PCDATA)>
<!ELEMENT Oznake (Oznaka)*>
<!ELEMENT Oznaka (#PCDATA)>
<!ELEMENT Akcije (Akcija)*>
<!ELEMENT Akcija EMPTY>
<!ATTLIST Cena valuta (yen | eur | rsd | den | fun | pnd ) "rsd">
<!ATTLIST Akcija cena CDATA #REQUIRED>
<!ATTLIST Akcija datumIsteka CDATA #REQUIRED>

=== MarkJov/ist2021/XML/proizvodi.xml
<?xml version="1.0"?>
<!-- <!DOCTYPE note SYSTEM "proizvodi.dtd"> -->
<Proizvodi>
    <Proizvod xmlns="https://www.w3schools.com"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="proizvodi.xsd">
        <Kategorija>Laptop</Kategorija>
        <Cena valuta="rsd">2450</Cena>
        <TekstOglasa>Opis oglasa</TekstOglasa>
        <Oznake>
            <Oznaka>akcija</Oznaka>
        </Oznake>
        <Akcije>
            <Akcija cena="789" datumIsteka="1134"></Akcija>
        </Akcije>
    </Proizvod> 
</Proizvodi>
